config/routes.rb
Rails.application.routes.draw do

  devise_for :authors
  
  root to: 'blog/posts#home'
  
  namespace :authors do
    get '/account' => 'accounts#edit', as: :account
    put '/info' => 'accounts#update_info', as: :info
    put '/change_password' => 'accounts#change_password', as: :change_password
    resources :posts do
     put 'publish' => 'posts#publish', on: :member
     put 'unpublish' => 'posts#unpublish', on: :member
    end
  end  
  
  scope module: 'blog' do
    
    get 'impressum', to: 'pages#impressum'
    get 'cookies', to: 'pages#cookies'
    
    resources :contacts, only: :create
    get 'Kontakt_Formular', to: 'contacts#new', as: 'new_contact'
    
    get 'produkte', to: 'products#produkte'
    get 'sicherungsbrille', to: 'products#sicherungsbrille'
    get 'brillen_etui', to: 'products#brillen_etui'
    
    get 'stories', to: 'posts#index'
    get 'posts' => 'posts#index', as: :posts
    get 'posts/:id' => 'posts#show', as: :post
    
  end
  

end

app/views/layouts/_facebook.html.erb
<div class="fb-page" data-href="https://www.facebook.com/Topside-2082532521973737/" data-tabs="timeline" data-width="300" data-height="337" data-small-header="true" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="true"><blockquote cite="https://www.facebook.com/Topside-2082532521973737/" class="fb-xfbml-parse-ignore"><a href="https://www.facebook.com/Topside-2082532521973737/">Topside</a></blockquote></div>

app/views/layouts/_footer.html.erb
  <%= render 'cookies_eu/consent_banner', link: cookies_path, target: '_blank' %>
  <footer>
    <div class="container">
			<div class="footer_all">
				<div class="row col-md-4">
				  <%=image_tag("logo/logo_inverted.gif", size: "150x38", alt: "Example Image", class: "footer_logo")%>
				  
 					<div class="footer_under_logo">
   					<p>Wir haben das Ziel dich mit unseren Produkten und Stories beim Sport zu unterstützen. So fällt dir der Sport leichter und du hast noch mehr Spaß am Sport. <br><br>
   					<strong>Topside</strong> - <strong>enjoy your sport.</strong></p>
 					</div>
 					
					<div class="admin-bereich">
						<% if author_signed_in? %>
			        <li class="nav-item dropdown author-nav">
			          <a class="nav-link dropdown-toggle <%= yield(:author) %>" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
			            <%= image_tag(current_author.gravatar_image_url) %>
			            <%= current_author.display_name %>
			          </a>
			          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
			            <%= link_to 'My posts', authors_posts_path, class: "dropdown-item" %>
			            <%= link_to 'Account', authors_account_path, class: "dropdown-item" %>
			            <%= link_to 'Logout', destroy_author_session_path, method: :delete, class: "dropdown-item" %>
			          </div>
			        </li>
			      <% end %>
				    
				    <div class="btn btn-default navbar-btn standard-link">
				      <%= link_to 'Admin Bereich', authors_posts_path, class: "nav-link #{yield(:author)}" %>
				    </div>
					</div>
					
				</div>
			</div>

			<div class="row col-md-4">
				<div class="footer_mid">
					
					<div class="mid-fooder-links">
						<h4>Topside auf amazon</h4>
						<h4><a href="#">aes aseva aeses</a></h4>
					</div>
					<div class="mid-fooder-links">
						<h4>Nützliche Listen</h4>
						<h4><a href="#">aes aseva aeses</a></h4>
					</div>
					<div class="mid-fooder-links">
						<h4>Werde Topside Partner</h4>
						<h4><a href="#">aes aseva aeses</a></h4>
					</div>
					<div class="mid-fooder-links">
						<h4>Du bist Topside Fan - wir freuen uns und unterstützen dich dabei gerne!</h4>
						<h4><a href="#">aes aseva aeses</a></h4>
					</div>

				</div>
			</div>
			
			<div class="row col-md-4 center">
		 		<div class="footer-small-right">
	 			  <%= link_to "Impressum", impressum_path %><br>
	 			</div>
	 			
	 			<div class="footer-small-right">
	 			  <%= link_to "Datenschutzbestimmung", cookies_path %><br>
	 			</div>
	 			
	 			<div class="footer-small-right">
	 			  <a href="https://www.instagram.com/p/RTTaxToOwN/">Folge uns auf Instgram</a><br>
	 			</div>
	 			
	 			<div class="footer-small-right">
					<h4>Folge uns auf Facebook</h4>
					<div class="fb-like" data-href="https://www.facebook.com/Topside-2082532521973737/" data-layout="standard" data-action="like" data-size="small" data-show-faces="true" data-share="true"></div>
				</div>
				
				<div class="row col-md-4">
					<address>
						<p><strong>Adresse:</strong><br><br>
						<strong>Telefon:</strong><br>
						<strong>Email:</strong>
					
					</address>
				</div>
				<div class="row col-md-8">
					<p>
						Kupferstraße 25,
						70565 Stuttgart <br>
						+49 711 91288697 <br>
						info@topside-sport.de</p>
				</div>
			</div>
		</div>
  </footer>
</html>

app/views/layouts/_instagram.html.erb
<blockquote class="instagram-media" data-instgrm-version="7" style=" background:#FFF; border:0; border-radius:3px; box-shadow:0 0 1px 0 rgba(0,0,0,0.5),0 1px 10px 0 rgba(0,0,0,0.15); margin: 1px; max-width:658px; padding:0; width:99.375%; width:-webkit-calc(100% - 2px); width:calc(100% - 2px);">
  <div style="padding:8px;"> 
    <div style=" background:#F8F8F8; line-height:0; margin-top:40px; padding:50% 0; text-align:center; width:100%;"> 
      <div style=" background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACwAAAAsCAMAAAApWqozAAAABGdBTUEAALGPC/xhBQAAAAFzUkdCAK7OHOkAAAAMUExURczMzPf399fX1+bm5mzY9AMAAADiSURBVDjLvZXbEsMgCES5/P8/t9FuRVCRmU73JWlzosgSIIZURCjo/ad+EQJJB4Hv8BFt+IDpQoCx1wjOSBFhh2XssxEIYn3ulI/6MNReE07UIWJEv8UEOWDS88LY97kqyTliJKKtuYBbruAyVh5wOHiXmpi5we58Ek028czwyuQdLKPG1Bkb4NnM+VeAnfHqn1k4+GPT6uGQcvu2h2OVuIf/gWUFyy8OWEpdyZSa3aVCqpVoVvzZZ2VTnn2wU8qzVjDDetO90GSy9mVLqtgYSy231MxrY6I2gGqjrTY0L8fxCxfCBbhWrsYYAAAAAElFTkSuQmCC); 
      display:block; height:44px; margin:0 auto -44px; position:relative; top:-22px; width:44px;">
      </div>
    </div>
    
    <p style=" color:#c9c8cd; font-family:Arial,sans-serif; font-size:14px; line-height:17px; margin-bottom:0; margin-top:8px; overflow:hidden; padding:8px 0 7px; text-align:center; text-overflow:ellipsis; white-space:nowrap;">
      <a href="https://www.instagram.com/p/RTTaxToOwN/" 
        style=" color:#c9c8cd; font-family:Arial,sans-serif; font-size:14px; font-style:normal; font-weight:normal; line-height:17px; text-decoration:none;" target="_blank">
        Ein Beitrag geteilt von Topside (@topside_sport)
      </a> 
      am 
      <time style=" font-family:Arial,sans-serif; font-size:14px; line-height:17px;" datetime="2012-10-27T21:55:54+00:00">27. Okt 2012 um 14:55 Uhr
      </time>
    </p>
    
  </div>
</blockquote> 
<script async defer src="//platform.instagram.com/en_US/embeds.js">
</script>

app/views/layouts/_navbar.html.erb
<div class="collapse" id="exCollapsingNavbar">
  <div class="collapse-bg p-a-1">
    <div class='card'>
      
      <ul class="list-group list-group-flush">
        <li class="list-group-item">
          <%= link_to "Home", root_path, class: "nav-link #{yield(:home_active)}" %>
        </li>
        <li class="list-group-item">
          <%= link_to 'Stories', stories_path, class: "nav-link #{yield(:stories_active)}" %>
        </li>
        <li class="list-group-item">
          <%= link_to "Produkte", produkte_path, class: "nav-link #{yield(:produkte_active)}" %>
        </li>
        <li class="list-group-item">
          <%= link_to "Kontakt", new_contact_path, class: "nav-link #{yield(:kontakt_active)}" %>
        </li>
      </ul>
      
    </div>
  </div>
</div>

<nav class="navbar navbar-light bg-faded">
  <div class='container'>
    
    <div class="logo">
      <%= link_to root_path do %>
        <%=image_tag("logo/logo_inverted.gif", size: "200x51", class: "logo2")%>
      <% end %>
    </div>
    
    <button class="navbar-toggler hidden-sm-up pull-xs-right" type="button" data-toggle="collapse" data-target="#exCollapsingNavbar">
      &#9776;
    </button>
    
    <ul class="nav navbar-nav pull-sm-right hidden-xs-down">
      <li class="nav-item">
        <%= link_to "Home", root_path, class: "nav-link #{yield(:home_active)}" %>
      </li>
      <li class="nav-item">
        <%= link_to 'Stories', stories_path, class: "nav-link #{yield(:stories_active)}" %>
      </li>
      <li class="nav-item">
        <%= link_to "Produkte", produkte_path, class: "nav-link #{yield(:produkte_active)}" %>
      </li>
      <li class="nav-item">
        <%= link_to "Kontakt", new_contact_path, class: "nav-link #{yield(:kontakt_active)}" %>
      </li>
    </ul>
    
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:page_title) %> Topside</title>
    <%= csrf_meta_tags %>
    <link href="//fonts.googleapis.com/css?family=Open+Sans:400,700,800" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'cookies_eu/consent_banner' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    
    <div class="main-background">
      <div class="container">
        <% flash.each do |type, msg| %>
          <%= content_tag :div, msg, class: "alert alert-#{type}" %>
        <% end %>
      </div>
      
      <div class="grund <%= controller_name %> <%= action_name %>">
				<%= yield %> <!-- Grund für jede seite die ganze datei und yield holt den rest der view files> -->
      </div>
    </div>
    
    
  </body>
  
  <footer>
    <div class="container">
			<div class="footer_all">
				<div class="col-md-4">
				  <%=image_tag("logo/logo.gif", size: "150x38", alt: "Example Image", class: "footer_logo")%>
				  
 					<div class="footer_under_logo">
   					<p>Wir haben das Ziel dich mit unseren Produkten und Stories beim Sport zu unterstützen. So fällt dir der Sport leichter und du hast noch mehr Spaß am Sport. <br><br>
   					<strong>Topside</strong> - <strong>enjoy your sport.</strong></p>
 					</div>
 					
 					<div class="impressum_footer">
 					  <%= link_to "Impressum", impressum_path %><br>
 					</div>
 					
					<address>
						<strong>Adresse:</strong><br>
						Kupferstraße 25<br>
						70565 Stuttgart<br>
					</address>
						<abbr title="Telefon"><strong>Telefon:</strong></abbr> +49 <br>
						<abbr title="Email:"><strong>Email:</strong></abbr> info@topside-sport.de <br>

					<div class="unten_login">

          </div>
				</div>
			</div>

					<div class="col-md-4 col_last">

						<div class="footer_mid">
							<h4>Instagramm Feed oder letzten Posts</h4>

							<div id="post-list-footer">
								<div class="spost clearfix">
									<div class="entry-c">
										<div class="entry-title">
											<h4><a href="#">aes aseva aeses</a></h4>
										</div>
										<ul class="entry-meta">
											<li>10th July 2014</li>
										</ul>
									</div>
								</div>

								<div class="spost clearfix">
									<div class="entry-c">
										<div class="entry-title">
											<h4><a href="#">Elsfgfdhfgfh fh fdhfg dfghgfdh dfi</a></h4>
										</div>
										<ul class="entry-meta">
											<li>10th July 2014</li>
										</ul>
									</div>
								</div>

								<div class="spost clearfix">
									<div class="entry-c">
										<div class="entry-title">
											<h4><a href="#">eEDedsfgdf dsg dds df dfgzhsi</a></h4>
										</div>
										<ul class="entry-meta">
											<li>10th July 2014</li>
										</ul>
									</div>
								</div>
								
								<div class="btn btn-default navbar-btn standard-link">
						      <%= link_to 'Admin Bereich', stories_path %>
						    </div>

							</div>
						</div>
					</div>
					<div class="col-md-4">
						<div class="fb_footer">
              <div class="fb-page" data-href="https://www.facebook.com/Topside-2082532521973737/" 
                data-tabs="timeline" data-width="250" data-height="350" data-small-header="true" 
                data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="true">
                  <blockquote cite="https://www.facebook.com/Topside-2082532521973737/" class="fb-xfbml-parse-ignore">
                    <a href="https://www.facebook.com/Topside-2082532521973737/">Topside</a>
                  </blockquote>
                </div>
						</div>
					</div>
				</div><!-- .footer-widgets-wrap end -->
			</div>
		</div>
  </footer>
</html>

app/views/layouts/author.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:page_title) %></title>
    <%= csrf_meta_tags %>
    <link href="//fonts.googleapis.com/css?family=Open+Sans:400,700,800" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cloud.tinymce.com/stable/tinymce.min.js?apiKey=8j0nor1czlyiasxh019j4kc0wnhlshn8x59ckolhx1esxoix"></script>
    <!-- Google analytics deaktivieren -->
    <script type="text/javascript">
      var gaProperty = 'UA-XXXXXXX-X';
      var disableStr = 'ga-disable-' + gaProperty;
      if (document.cookie.indexOf(disableStr + '=true') > -1) {
      window[disableStr] = true;
      }
      function gaOptout() {
      document.cookie = disableStr + '=true; expires=Thu, 31 Dec 2099 23:59:59 UTC; path=/';
      window[disableStr] = true;
      }
    </script>
    <!-- Google analytics-->
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
    
      ga('create', 'UA-98997741-1', 'auto');
      ga('send', 'pageview');
    
    </script>
  </head>

  <body>
    <div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/de_DE/sdk.js#xfbml=1&version=v2.9";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
    
    
    <%= render 'layouts/navbar' %>
    
    
    <div class="home-callout">
      <h1><%= yield(:page_title2) %></h1>
    </div>
    
    <div class="center-homepage">
      <div class="container">
        <% if flash.any? %>
          <% flash.keys.each do |key| %>
            <div class="alert alert-<%= key.to_s %> alert-dismissible" role="alert">
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
              <%= flash[key] %>
            </div>
          <% end %>
        <% end %>
      </div>
      
      <div class="grund <%= controller_name %> <%= action_name %>">
  		  <%= yield %> <!-- Grund für jede seite die ganze datei und yield holt den rest der view files> -->
      </div>
    </div>
    
    
    <%= render 'layouts/footer' %>
    
  </body>
  
  

</html>

app/views/layouts/blog.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:page_title) %></title>
    <%= csrf_meta_tags %>
    <link href="https://fonts.googleapis.com/css?family=Merriweather:400,400i,700|Montserrat:300,400,700" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- Google analytics deaktivieren -->
    <script type="text/javascript">
      var gaProperty = 'UA-XXXXXXX-X';
      var disableStr = 'ga-disable-' + gaProperty;
      if (document.cookie.indexOf(disableStr + '=true') > -1) {
      window[disableStr] = true;
      }
      function gaOptout() {
      document.cookie = disableStr + '=true; expires=Thu, 31 Dec 2099 23:59:59 UTC; path=/';
      window[disableStr] = true;
      }
    </script>
    <!-- Google analytics-->
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
    
      ga('create', 'UA-98997741-1', 'auto');
      ga('send', 'pageview');
    
    </script>
  </head>

  <body>
    <div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/de_DE/sdk.js#xfbml=1&version=v2.9";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
    
  
  <%= render 'layouts/navbar' %>
  
  
    <div class="home-callout text-center">
      <h1><%= yield(:page_title) %><</h1>
    </div>
    
    <div class="center-homepage">
      <div class="container">
        <% flash.each do |type, msg| %>
          <%= content_tag :div, msg, class: "alert alert-#{type}" %>
        <% end %>
      </div>
      
      <div class="grund <%= controller_name %> <%= action_name %>">
    		<%= yield %> <!-- Grund für jede seite die ganze datei und yield holt den rest der view files> -->
      </div>
    </div>
    
    <%= render 'layouts/footer' %>

  
  </body>
  

</html>